name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java_version: ['1.6', '9.0.x', '12.0.2']
        os: [ubuntu-latest, windows-latest , macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{matrix.java_version}}
      uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java_version}}
        architecture: x64
    - name: Run tests
      run: sbt test
